### ISSUE TITLE
put a loader when a contact submit has been sent

### ISSUE THREAD

**Issue by raulfdm** [raulfdm/personal-website#35]
Following the CSS code to do that:
```css
.player .active-bg .buffering {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    margin: auto;
    display: none;
    width: 100px;
    height: 100px;
    border-top: 2px solid rgba(255,255,255,.2);
    border-right: 2px solid rgba(255,255,255,.2);
    border-bottom: 2px solid rgba(255,255,255,.2);
    border-left: 2px solid #fff;
    -webkit-border-radius: 50%;
    -moz-border-radius: 50%;
    -ms-border-radius: 50%;
    border-radius: 50%;
    -webkit-transform: translateZ(0);
    -ms-transform: translateZ(0);
    transform: translateZ(0);
    -webkit-animation: buffering 1.1s infinite linear;
    animation: buffering 1.1s infinite linear;
}
2102.css:1
*, *:focus, *:active {
    outline: none;
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}
```
